services:

  sonarr:
    image: linuxserver/sonarr
    container_name: sonarr
    networks:
      - local-sonarr
      - shared
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Zurich
    volumes:
      - /media/arr/sonarr/config:/config
      - /media/arr/sonarr/tvseries:/tv
      - /media/arr/sonarr/tvseriesDE:/tvDE
      - /media/arr/sonarr/tvseriesFR:/tvFR
      - /media/arr/sonarr/anime:/anime
      - /media/arr/sonarr/animeDE:/animeDE
      - /media/arr/sonarr/animeFR:/animeFR
      - /media/arr/sonarr/backup:/data/Backup
      - /media/arr/sabnzbd/downloads:/downloads
    ports:
      - 8989:8989
    restart: unless-stopped

  radarr:
    image: linuxserver/radarr
    container_name: radarr
    networks:
      - local-radarr
      - shared
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Zurich
    volumes:
      - /media/arr/radarr/data:/config
      - /media/arr/radarr/backup:/data/Backup
      - /media/arr/radarr/movies:/movies
      - /media/arr/radarr/moviesDE:/moviesDE
      - /media/arr/radarr/moviesFR:/moviesFR
      - /media/arr/sabnzbd/downloads:/downloads
    ports:
      - 7878:7878
    restart: unless-stopped

  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    networks:
      - local-prowlarr
      - shared
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Zurich
    volumes:
      - /media/arr/prowlarr/data:/config
    ports:
      - 9696:9696
    restart: unless-stopped

  sabnzbd:
    image: lscr.io/linuxserver/sabnzbd:latest
    container_name: sabnzbd
    networks:
      - local-sabnzbd
      - shared
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Zurich
    volumes:
      - /media/arr/sabnzbd/config:/config
      - /media/arr/sabnzbd/downloads/incomplete:/downloads/incomplete
      - /media/arr/sabnzbd/downloads:/downloads
    ports:
      - 8080:8080
    restart: unless-stopped

  profilarr:
    image: santiagosayshey/profilarr:latest
    container_name: profilarr
    networks:
      - local-profilarr
      - shared
    ports:
        - 6868:6868
    volumes:
        - /media/arr/profilarr/config:/config
    environment:
        - TZ=Europe/Zurich
    restart: unless-stopped

networks:
  local-sonarr:
  local-radarr:
  local-prowlarr:
  local-profilarr:
  local-sabnzbd:
  shared:
    external: true