services:

  homarr:
    image: ghcr.io/ajnart/homarr:latest
    container_name: homarr
    hostname: homarr
    networks:
      - local-homarr
      - shared
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Zurich
    volumes:
      - ./homarr/configs:/app/data/configs
      - ./homarr/icons:/app/public/icons
    depends_on:
      - jellyfin
      - jellyseerr
      - sonarr
      - radarr
    ports:
      - 7575:7575
    restart: unless-stopped

networks:
  local-homarr:
  shared:
    external: true