services:

  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    networks:
      - local-jellyfin
      - shared
    volumes:
      - /media/arr/jellyfin/config:/config
      - /media/arr/sonarr/tvseries:/data/tvshows
      - /media/arr/sonarr/tvseriesDE:/data/tvshowsDE
      - /media/arr/sonarr/tvseriesFR:/data/tvshowsFR
      - /media/arr/radarr/movies:/data/movies
      - /media/arr/radarr/moviesDE:/data/moviesDE
      - /media/arr/radarr/moviesFR:/data/moviesFR
    ports:
      - 8096:8096
      - 8920:8920
      - 7359:7359/udp
      - 1900:1900/udp
    restart: unless-stopped

  jellyseerr:
    image: fallenbagel/jellyseerr:latest
    container_name: jellyseerr
    networks:
      - local-jellyseerr
      - shared
    environment:
      - LOG_LEVEL=debug
      - TZ=Europe/Zurich
    depends_on:
      - jellyfin
    ports:
      - 5055:5055
    volumes:
      - /media/arr/jellyseerr/config:/app/config
    restart: unless-stopped

  homarr:
    image: ghcr.io/homarr-labs/homarr:latest
    container_name: homarr
    hostname: homarr
    networks:
      - local-homarr
      - shared
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Zurich
      - SECRET_ENCRYPTION_KEY=2e3a56e8c4f4308bc4c8982d5ef5085297536af0a9044e74ea4c506850a7b721
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./homarr/configs:/app/data/configs
      - ./homarr/icons:/app/public/icons
      - ./homarr/data:/appdata
    depends_on:
      - jellyfin
      - jellyseerr
    ports:
      - 7575:7575
    restart: unless-stopped

networks:
  local-jellyfin:
  local-jellyseerr:
  local-homarr:
  shared:
    external: true