services:

  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    networks:
      - local-jellyfin
      - shared
    volumes:
      - /media/arr/jellyfin/config:/config
      - /media/arr/sonarr/tvseries:/data/tvshows
      - /media/arr/radarr/movies:/data/movies
      - /media/arr/lidarr/music:/data/music
    ports:
      - 8096:8096
      - 8920:8920
      - 7359:7359/udp
      - 1900:1900/udp
    restart: unless-stopped

  jellyseer:
    image: fallenbagel/jellyseerr:latest
    container_name: jellyseer
    networks:
      - local-jellyseer
      - shared
    environment:
      - LOG_LEVEL=debug
      - TZ=Europe/Zurich
    depends_on:
      - jellyfin
    ports:
      - 5055:5055
    volumes:
      - /media/arr/jellyseer/config:/app/config
    restart: unless-stopped

networks:
  local-jellyfin:
  local-jellyseer:
  shared:
    external: true